/*export const schema = {
  name: "John Doe Increment(1)",
  age: 32,
  address: {
    street: "123 Main St",
    city: "Random(string, 10, 2)",
    state: "CA",
    zip: "12345",
  },
  phone: [
    {
      type: "home",
      number:
        "Random(int, 100, 999)-Random(int, 100, 999)-Random(int, 1000, 9999)",
    },
    {
      type: "cell",
      number:
        "Random(int, 100, 999)-Random(int, 100, 999)-Random(int, 1000, 9999)",
    },
  ],
};
*/
export const schema = {
  name: "Random(name)",
  age: "Random(int, 1, 100)",
  url: "/api/Random(int, 1, 200)/this-Increment(1)-Random(float, 2, 50) Decrement(10)-Random(string, 2, 13).jpg",
  description: "Random(string, 5, 1) Increment(1)",
  email: "Random(email)",
  "configGlossary:poweredByIcon": "/images/Increment(1)",
  stage: {
    stage_name: "Random(string, 5, 1) Increment(1)",
    stage_description: "Random(string, 5, 1) Increment(1)",
    place: {
      place_name: "Random(string, 5, 1) Increment(1)",
      place_description: "Random(text, 5) Increment(1)",
    },
    "servlet-name": "cofaxTools",
    "servlet-class": "org.cofax.cms.CofaxToolsServlet",
    "init-param": {
      templatePath: {
        value: "toolstemplates/",
        description: "Path to template",
      },
      log2: 1,
      logLocation1: {
        value: "/usr/local/tomcat/logs/CofaxTools.log",
        description: "Log file location",
      },
      log: 1,
      logLocation: "/usr/local/tomcat/logs/CofaxTools.log",
      logMaxSize: "",
      dataLog: 1,
      dataLogLocation: "/usr/local/tomcat/logs/dataLog.log",
      dataLogMaxSize: "",
      removePageCache: "/content/admin/remove?cache=pages&id=",
      removeTemplateCache: "/content/admin/remove?cache=templates&id=",
      fileTransferFolder:
        "/usr/local/tomcat/webapps/content/fileTransferFolder",
      lookInContext: 1,
      adminGroupID: 4,
    },
    "initialization-param": {
      "configGlossary:installationAt": "Philadelphia, PA",
      "configGlossary:adminEmail": "ksm@pobox.com",
      "configGlossary:poweredBy": "Cofax",
      "configGlossary:poweredByIcon": "/images/cofax.gif",
      "configGlossary:staticPath": "/content/static",
      templateProcessorClass: "org.cofax.WysiwygTemplate",
      templateLoaderClass: "org.cofax.FilesTemplateLoader",
      templatePath: "templates",
      templateOverridePath: "",
      defaultListTemplate: "listTemplate.htm",
      defaultFileTemplate: "articleTemplate.htm",
      useJSP: false,
      jspListTemplate: "listTemplate.jsp",
      jspFileTemplate: "articleTemplate.jsp",
      cachePackageTagsTrack: "Random(int, 1, 100)",
      cachePackageTagsStore: "Random(int, 1, 100)",
      cachePackageTagsRefresh: "Random(int, 1, 100)",
      cacheTemplatesTrack: "Random(int, 1, 100)",
      cacheTemplatesStore: "Random(int, 1, 100)",
      cacheTemplatesRefresh: "Random(int, 1, 100)",
      cachePagesTrack: "Random(int, 1, 100)",
      cachePagesStore: "Random(int, 1, 100)",
      cachePagesRefresh: "Random(int, 1, 100)",
      cachePagesDirtyRead: "Random(int, 1, 100)",
      searchEngineListTemplate: "forSearchEnginesList-Random(float, 1, 5).htm",
      searchEngineFileTemplate: "forSearchEngines-Increment(0).htm",
      searchEngineRobotsDb: "WEB-INF/robots.db",
      useDataStore: true,
      dataStoreClass: "org.cofax.SqlDataStore",
      redirectionClass: "org.cofax.SqlRedirection",
      dataStoreName: "cofax",
      dataStoreDriver: "com.microsoft.jdbc.sqlserver.SQLServerDriver",
      dataStoreUrl:
        "jdbc:microsoft:sqlserver://LOCALHOST:1433;DatabaseName=goon",
      dataStoreUser: "sa",
      dataStorePassword: "dataStoreTestQuery",
      dataStoreTestQuery: "SET NOCOUNT ON;select test='test';",
      dataStoreLogFile: "/usr/local/tomcat/logs/datastore.log",
      dataStoreInitConns: 10,
      dataStoreMaxConns: 100,
      dataStoreConnUsageLimit: 100,
      dataStoreLogLevel: "debug",
      maxUrlLength: "Random(int, 1, 500)",
    },
  },
};
